name: Deploy latest SNAPSHOT to Clojars
on:
  push:
    branches:
      - master

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          lein: latest

      - name: Detect release branch
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "LEIN_REVISIONS_RELEASE=true" >> $GITHUB_ENV
          echo "LEIN_REVISIONS_PRERELEASE=true" >> $GITHUB_ENV

      # eventually this will have something better, for now this is fine
      - name: Detect revision increment adjustment
        run: echo "LEIN_REVISIONS_ADJUSTMENTS=patch" >> $GITHUB_ENV

      - name: Deploy to Clojars
        run: lein deploy clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}

      #- name: Extract version
      #  id: version
      #  run: echo "::set-output name=version::$(lein pprint :version | tr -d '\"')"
#
      #- name: Create tag
      #  uses: actions/github-script@v6
      #  with:
      #    script: |
      #      github.rest.git.createRef({
      #        owner: context.repo.owner,
      #        repo: context.repo.repo,
      #        ref: "refs/tags/v${{steps.version.outputs.version}}",
      #        sha: context.sha
      #      })
