name: Deploy to Clojars
on:
  push:
    branches:
      - master

env:
  CI: yes
  LEIN_REVISIONS_RELEASE: yes

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          lein: latest

      - name: Debug Actions runner
         run: lein pprint :version && git describe --tags --dirty --lon

      - name: Deploy to Clojars
        run: lein deploy clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}

      - name: Extract version
        id: version
        run: echo "::set-output name=version::$(lein pprint :version | tr -d '\"')"

      - name: Tag the release
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{steps.version.outputs.version }}

      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{steps.version.outputs.version }}",
              sha: context.sha
            })
